version: '2'
services:
  testws:
    image: registry-internal.cn-hangzhou.aliyuncs.com/yontact/testws
    restart: always
    labels:
      aliyun.proxy.VIRTUAL_HOST: http://testws.58ee.top,ws://testws.58ee.top
      aliyun.rolling_updates: "true"
      aliyun.scale: "1"

